### ISSUE TITLE
PHP extension_dir not set correctly

### ISSUE THREAD

**Issue by miniduikboot** [paladox/Arcanist-installer-for-windows#1]
I just installed Arcanist using your installer on a brand new install of Windows and since PHP was not installed, I installed it as well, but some extra steps must be taken: 
- VC14 redistributable must be installed, for that, see my other issue (#2)
- PHP's extension_dir is not set, causing PHP to load extensions from C:\PHP, but since we don't have PHP installed there, this causes issues as displayed in the image below:

![capture](https://cloud.githubusercontent.com/assets/5243971/14488151/fba5d034-0166-11e6-9a04-75cbd07b414c.PNG)

This last point can easily be fixed by adding a line

```
extension_dir = "C:\Program Files\Arcanist\php\x64\ext"
```

to php.ini. Issue is that this is different for other systems, so this must be done by the installer. Please fix.

**Comment by paladox** [comment]
Thanks for the bug report. I will go an update php ini to use the correct path to the ext.

**Comment by paladox** [comment]
@JustHev Hi please could you try https://github.com/paladox/Arcanist-installer-for-windows/releases/tag/0.0 setup.exe to see if this fixes it for you please.

**Comment by miniduikboot** [comment]
@paladox Thank you for the quick fix, this works perfectly. Just that my antivirus decided that this is the perfect executable to go guns blazing on, but that should be fixed in time after trust builds up

**Comment by paladox** [comment]
@JustHev yep, I think I have to sign the installs but I'm not sure how to do that. All php files are from the official binarys, the only thing I changed was I added the php.ini file otherwise the user would have to manually create it.
