### ISSUE TITLE
VC14 redistributable not installed

### ISSUE THREAD

**Issue by miniduikboot** [paladox/Arcanist-installer-for-windows#2]
I just installed Arcanist using your installer on a brand new install of Windows and since PHP was not installed, I installed it as well, but some extra steps must be taken: 
- PHP's extension_dir is not set, see my other issue, #1.
- Visual C++ Redistributable for Visual Studio 2015 was not installed on my system, causing PHP not to run because `vcruntime140.dll` was not present. This was fixed by installing the following package from Microsoft: https://www.microsoft.com/en-us/download/details.aspx?id=48145 
  
  If it is easy to check if this package is not installed, please add a check.

**Comment by paladox** [comment]
Thankyou for reporting this.

**Comment by paladox** [comment]
Fixed in https://github.com/paladox/Arcanist-installer-for-windows/commit/920954035e69fab92cd393d856a28b8579ac6704

**Comment by paladox** [comment]
@JustHev please could you try https://github.com/paladox/Arcanist-installer-for-windows/releases/tag/1.1.2 setup.exe.
