### ISSUE TITLE
Installer sets wrong paths in x64 installer

### ISSUE THREAD

**Issue by MGChecker** [paladox/Arcanist-installer-for-windows#3]
After I installed Arcanist, the commands php and arc didn't work in the cmd. (Using Windows 10 Home) After a bit of research I found out that the problem were the paths created by the installer in the path variable, the final \ was missing, after I added it everything worked as expected. It would be nice if this little issue would be fixed anytime soon.

I don't know if this also happens if you use the x86 installer, I didn't test it.

**Comment by paladox** [comment]
Hi, Thanks, would you be able to submit a pull please?

**Comment by MGChecker** [comment]
Unfortunately I don't have any knowledge reagrding .exe files and thier coding.

**Comment by paladox** [comment]
@MGChecker oh. You only need to do what you did to your file to get it working.

**Comment by MGChecker** [comment]
I didn't do anything to the file, I fixed the problem manually by editing the path variable.

**Comment by paladox** [comment]
Oh. What variable did you change? Could you paste the before and after please?

**Comment by MGChecker** [comment]
Environment variables ( https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10 ) -> System variables -> Path -> Edit… ->

C:\Program Files\Arcanist_Win\arcanist\bin -> Edit -> C:\Program Files\Arcanist_Win\arcanist\bin\
C:\Program Files\Arcanist_Win\php\x64 -> Edit -> C:\Program Files\Arcanist_Win\php\x64\

**Comment by paladox** [comment]
@MGChecker something like https://github.com/paladox/Arcanist-installer-for-windows/pull/4 ?

**Comment by MGChecker** [comment]
Oh, now I get where the actual installer data is saved ^^ You fixed the Uninstaller, but not the Installer. Lines 58 to 60 are the corresponding lines, I guess. Lines 43 and 44 seem to work even though the \ is missing.

I would have commited that to your pull request branch, but I'm unable to do so.

**Comment by paladox** [comment]
@MGChecker and this https://github.com/paladox/Arcanist-installer-for-windows/commit/70875f9cfe51db11ae36c2ce19b473bd905531ad ?

**Comment by MGChecker** [comment]
As I said, I don't thinks these lines are important, because the files are already unpacked in the right places at the moment, but I think it will also work this way. The major problem still are lines 58 to 60.

**Comment by paladox** [comment]
@MGChecker  https://github.com/paladox/Arcanist-installer-for-windows/commit/5dc5159ffa586c701702cfc3371c50a5012ff4b4 ?

**Comment by paladox** [comment]
bump

**Comment by MGChecker** [comment]
Oh, didn't know this was still open. That is wahat I meant, I think it will work.
